import asyncio
import os
import signal
import threading
import traceback
import weakref
from collections.abc import Callable
from concurrent.futures import ProcessPoolExecutor
from concurrent.futures.process import BrokenProcessPool
from functools import partial

from areal.utils import logging
from areal.utils.constants import (
    PROCESS_KILL_GRACEFUL_TIMEOUT_SECONDS,
    REWARD_CONSECUTIVE_TIMEOUT_THRESHOLD,
    REWARD_TIMEOUT_SECONDS,
)
from areal.utils.proc import kill_process_tree

logger = logging.getLogger("Reward API")


def _get_worker_pids(executor: ProcessPoolExecutor) -> list[int]:
    """Extract worker process IDs from ProcessPoolExecutor."""
    pids = []
    if hasattr(executor, '_processes'):
        # Internal CPython implementation: executor has _processes dict
        pids = list(executor._processes.keys())
    return pids


def _get_device_count_safely() -> int:
    """
    Safely get device count without initializing CUDA context.
    """
    gpu_types = ["nvidia", "davinci"]
    try:
        if os.path.exists("/dev"):
            for gpu_type in gpu_types:
                devices = [
                    f
                    for f in os.listdir("/dev")
                    if f.startswith(gpu_type) and f[len(gpu_type) :].isdigit()
                ]
                if devices:
                    return len(devices)
    except (OSError, ValueError) as e:
        # /dev doesn't exist or can't read (e.g., Windows, macOS)
        logger.debug(f"Could not read device list from /dev, using fallback: {e}")

    # Fallback: assume 8 devices for cautious max_workers calculation
    return 8


def reward_fn(
    prompt: str,
    completions: str,
    prompt_ids: list[int],
    completion_ids: list[int],
    **kwargs,
):
    """This function is a placeholder for the reward function that will be used in the RLVR pipeline.

    In general, there's no restriction on the signature and implementation of this function in customized rollout workflows.
    It would be convinent to follow this signature and directly use it in our predefined rollout workflows.

    :param prompt: The string representing the task to be completed.
    :param completions: The string representing the trajectory generated by the model.
    :param prompt_ids: The token IDs of the prompt.
    :param completion_ids: The token IDs of the trajectory generated by the model.
    :param kwargs: Other attributes of the data in the dataset, such as solutions, input_outputs, etc.
        Any other attributes in the dataset will be passed as keyword arguments to this function.
    :rtype: float
    """


class AsyncRewardWrapper:
    """
    Wraps a synchronous reward function to make it async with timeout handling.
    Automatically manages ProcessPoolExecutor lifecycle based on instance count.
    Includes automatic recovery from broken process pools and process killing on timeout.
    """

    _executors = {}
    _instance_counts = {}
    _timeout_counts = {}  # Track consecutive timeouts per executor
    _future_to_pid = {}  # Map future objects to their worker PIDs for timeout handling
    _lock = threading.Lock()

    def __init__(
        self,
        reward_fn: Callable,
        timeout_seconds: float = REWARD_TIMEOUT_SECONDS,
        max_workers: int | None = None,
        max_retries: int = 3,
    ):
        self.reward_fn = reward_fn
        self.timeout_seconds = timeout_seconds
        if max_workers is None:
            cpu_count = os.cpu_count() or 1
            device_count = _get_device_count_safely()
            # Heuristic for max_workers: distribute CPU cores across devices,
            # then halve to be conservative, ensuring at least one worker.
            max_workers = max((cpu_count // device_count) // 2, 1)
        self.max_workers = max_workers
        self.max_retries = max_retries
        self._executor_key = max_workers

        with self._lock:
            if self._executor_key not in self._executors:
                self._executors[self._executor_key] = ProcessPoolExecutor(
                    max_workers=max_workers
                )
                self._instance_counts[self._executor_key] = 0
            self._instance_counts[self._executor_key] += 1

        weakref.finalize(self, AsyncRewardWrapper._cleanup_executor, max_workers)

    @classmethod
    def _cleanup_executor(cls, executor_key):
        """Called when an AsyncRewardWrapper instance is garbage collected"""
        with cls._lock:
            if executor_key in cls._instance_counts:
                cls._instance_counts[executor_key] -= 1
                if cls._instance_counts[executor_key] <= 0:
                    if executor_key in cls._executors:
                        executor = cls._executors.pop(executor_key)
                        executor.shutdown(wait=False, cancel_futures=True)
                        logger.debug(
                            f"ProcessPoolExecutor with {executor_key} workers shut down"
                        )
                    cls._instance_counts.pop(executor_key, None)

    @classmethod
    def _recreate_executor(cls, executor_key, max_workers):
        """Recreate a broken ProcessPoolExecutor"""
        with cls._lock:
            if executor_key in cls._executors:
                # Clean up the broken executor
                old_executor = cls._executors[executor_key]
                try:
                    old_executor.shutdown(wait=False)
                except Exception as e:
                    logger.warning(f"Error shutting down broken executor: {e}")

                # Create a new executor
                cls._executors[executor_key] = ProcessPoolExecutor(
                    max_workers=max_workers
                )
                logger.info(f"Recreated ProcessPoolExecutor with {max_workers} workers")
                return cls._executors[executor_key]
        return None

    async def __call__(self, *args, **kwargs) -> float:
        last_exception = None

        for attempt in range(self.max_retries + 1):
            with self._lock:
                executor = self._executors.get(self._executor_key)

            if executor is None:
                raise RuntimeError("ProcessPoolExecutor has been shut down")

            loop = asyncio.get_event_loop()
            try:
                future = loop.run_in_executor(
                    executor,
                    partial(self.reward_fn, *args, **kwargs),
                )

                # Track worker PIDs for timeout handling
                # Note: Worker assignment happens after submit, we estimate from executor state
                worker_pids = _get_worker_pids(executor)
                future_id = id(future)
                if worker_pids:
                    # Heuristic: round-robin assignment based on task count
                    # In practice, ProcessPoolExecutor maintains internal task queue
                    with self._lock:
                        self._future_to_pid[future_id] = worker_pids[0] if worker_pids else None

                reward = await asyncio.wait_for(
                    future,
                    timeout=self.timeout_seconds,
                )
                # Reset timeout counter on success and cleanup
                with self._lock:
                    self._timeout_counts[self._executor_key] = 0
                    self._future_to_pid.pop(future_id, None)
                return reward
            except asyncio.TimeoutError:
                # CRITICAL: Kill the worker process to prevent resource starvation
                # This is essential when reward functions (e.g., sympy) consume multiple GBs

                # Step 1: Kill the worker process FIRST to stop resource consumption immediately
                worker_pid = self._future_to_pid.get(id(future))
                if worker_pid is not None:
                    kill_process_tree(
                        parent_pid=worker_pid,
                        timeout=PROCESS_KILL_GRACEFUL_TIMEOUT_SECONDS,
                        include_parent=True,
                        graceful=True,
                    )
                    with self._lock:
                        self._future_to_pid.pop(id(future), None)

                # Step 2: Then cancel the future to clean up asyncio state
                # Note: This returns False (already executing), but helps with cleanup
                future.cancel()

                # Track consecutive timeouts per executor
                with self._lock:
                    timeout_count = self._timeout_counts.get(self._executor_key, 0) + 1
                    self._timeout_counts[self._executor_key] = timeout_count

                logger.warning(
                    f"Computing reward timeout after {self.timeout_seconds}s. "
                    f"Set reward to 0. (timeout #{timeout_count} for this executor) "
                    f"[Worker PID: {worker_pid}]"
                )

                # If too many consecutive timeouts, recreate entire executor to clear stuck workers
                if timeout_count >= REWARD_CONSECUTIVE_TIMEOUT_THRESHOLD:
                    logger.warning(
                        f"Too many timeouts ({timeout_count}). Recreating executor to clear all stuck processes."
                    )
                    self._recreate_executor(self._executor_key, self.max_workers)
                    with self._lock:
                        self._timeout_counts[self._executor_key] = 0

                return 0
            except BrokenProcessPool as e:
                last_exception = e
                logger.warning(
                    f"ProcessPoolExecutor broken (attempt {attempt + 1}/{self.max_retries + 1}). "
                    "Attempting to recreate..."
                )
                if attempt < self.max_retries:
                    # Try to recreate the executor
                    new_executor = self._recreate_executor(
                        self._executor_key, self.max_workers
                    )
                    if new_executor is None:
                        logger.error("Failed to recreate ProcessPoolExecutor")
                        break
                    # Continue to next attempt
                    continue
                else:
                    logger.error("Max retries exceeded for BrokenProcessPool.")
                    traceback.print_exc()
                    raise e
            except Exception as e:
                last_exception = e
                logger.error(f"Unexpected error in reward computation: {e}")
                if attempt < self.max_retries:
                    logger.info(
                        f"Retrying... (attempt {attempt + 1}/{self.max_retries + 1})"
                    )
                    continue
                else:
                    logger.error("Max retries exceeded for unexpected error.")
                    traceback.print_exc()
                    raise e

        # If we get here, all retries failed
        if last_exception:
            traceback.print_exc()
            raise last_exception
        else:
            raise RuntimeError("Reward computation failed after all retries.")
