"""Handler for computing log_prob_prox_t before weight updates.

This handler implements segment-wise decoupled PPO by computing proximal
policy logprobs at the next policy version (prox_t) before weight updates.

The key idea is to reduce variance of importance weights by using:
    π_prox_t / π_behavior instead of π_prox / π_behavior

Where prox_t is only 1 version ahead of behavior, reducing variance compared
to prox which could be many versions ahead (up to staleness window).
"""

import logging
from typing import Any

import torch

from areal.infrastructure import (
    FilterableQueue,
    ListCache,
    WorkflowEvents,
    get_event_bus,
)

logger = logging.getLogger(__name__)

# Key for tracking which version was used for prox_t recomputation
RECOMPUTE_VERSION_KEY = "_recompute_version"


def _extract_version(value: Any) -> int | None:
    """Extract version number from tensor or scalar value."""
    if value is None:
        return None
    try:
        tensor = torch.as_tensor(value)
        tensor = tensor.reshape(-1)
        if tensor.numel() == 0:
            return None
        return int(tensor[0].item())
    except Exception:
        try:
            return int(value)
        except Exception:
            return None


def _ensure_recompute_key(td) -> None:
    """Ensure the recompute tracking key exists with batch-aligned shape."""
    if td is None:
        return

    # Check if key already exists
    if RECOMPUTE_VERSION_KEY in (td.keys() if hasattr(td, "keys") else td):
        return

    # Check if versions field exists
    if "versions" not in (td.keys() if hasattr(td, "keys") else td):
        return

    # Get versions field
    versions = td.get("versions") if hasattr(td, "get") else td["versions"]
    if versions is None:
        return

    default_value = torch.full_like(versions[:, :1], -1, dtype=torch.int64)

    # Set key (handle both dict and TensorDict)
    try:
        if hasattr(td, "set"):
            td.set(RECOMPUTE_VERSION_KEY, default_value)
        else:
            td[RECOMPUTE_VERSION_KEY] = default_value
    except Exception as e:
        logger.debug(f"Could not set recompute key: {e}")


class ProxTLogprobHandler:
    """
    Handler for computing log_prob_prox_t before weight updates.

    This handler listens to BEFORE_WEIGHT_UPDATE events and scans the
    output queue and result cache for tokens generated by the previous
    policy version. It then recomputes their logprobs using the current
    policy (which is prox_t for those tokens) and patches the proximal_logprobs_t
    field.

    Parameters
    ----------
    output_queue : FilterableQueue
        Queue containing completed rollout results (injected)
    result_cache : ListCache
        Cache containing accepted rollout results (injected)

    Examples
    --------
    >>> from areal.core.app_container import app_container
    >>> handler = ProxTLogprobHandler(
    ...     output_queue=app_container.async_task_output_queue(),
    ...     result_cache=app_container.async_task_result_cache(),
    ... )
    >>> handler.register()
    """

    def __init__(
        self,
        output_queue: FilterableQueue,
        result_cache: ListCache,
    ):
        """Initialize handler with injected dependencies."""
        self.output_queue = output_queue
        self.result_cache = result_cache
        self._registered = False

    def register(self):
        """Register handler to PRE_WEIGHT_UPDATE event."""
        if self._registered:
            logger.warning("ProxTLogprobHandler already registered")
            return

        bus = get_event_bus()
        bus.connect(WorkflowEvents.PRE_WEIGHT_UPDATE, self.on_pre_weight_update)
        self._registered = True
        logger.info("ProxTLogprobHandler registered for PRE_WEIGHT_UPDATE events")

    def unregister(self):
        """Unregister handler from events."""
        if not self._registered:
            return

        bus = get_event_bus()
        bus.disconnect(WorkflowEvents.PRE_WEIGHT_UPDATE, self.on_pre_weight_update)
        self._registered = False
        logger.info("ProxTLogprobHandler unregistered")

    def on_pre_weight_update(self, sender, **kwargs):
        """
        Handle PRE_WEIGHT_UPDATE event.

        Scans output_queue and result_cache for tokens from previous policy version
        and recomputes their prox_t logprobs using the current policy.

        Parameters
        ----------
        sender : InferenceEngine
            The inference engine about to update weights
        **kwargs : dict
            Event data (not used - we get version directly from engine)
        """
        inference_engine = sender

        # Get current version directly from engine (per user feedback)
        if not hasattr(inference_engine, "get_version"):
            logger.warning("InferenceEngine does not have get_version method")
            return

        current_version = inference_engine.get_version()

        target_version = current_version - 1  # Tokens from previous version

        logger.info(
            f"[ProxTHandler] Processing prox_t recomputation: "
            f"current_version={current_version}, target_version={target_version}"
        )

        # Check if engine supports recomputation
        if not hasattr(inference_engine, "recompute_output_logprobs_sync"):
            logger.debug(
                "InferenceEngine does not support recompute_output_logprobs_sync, skipping"
            )
            return

        total_candidates = 0
        total_patched = 0

        # Scan and update output_queue
        def process_queue_item(item):
            nonlocal total_candidates, total_patched
            patched = self._try_recompute_item(
                item, target_version, current_version, inference_engine
            )
            if patched:
                total_patched += 1
                return item  # Keep item
            elif patched is not None:  # Candidate but not patched
                total_candidates += 1
                return item  # Keep item
            return item  # Keep all items

        self.output_queue.scan_and_update(process_queue_item)

        # Scan and update result_cache
        def process_cache_item(item):
            nonlocal total_candidates, total_patched
            patched = self._try_recompute_item(
                item, target_version, current_version, inference_engine
            )
            if patched:
                total_patched += 1
            elif patched is not None:
                total_candidates += 1
            return item  # Keep all items

        self.result_cache.scan_and_update(process_cache_item)

        logger.info(
            f"[ProxTHandler] Recomputation complete: "
            f"candidates={total_candidates}, patched={total_patched}"
        )

    def _try_recompute_item(
        self, td, target_version: int, current_version: int, inference_engine
    ) -> bool | None:
        """
        Try to recompute prox_t logprobs for an item.

        Returns:
            True if patched successfully
            False if candidate but not patched
            None if not a candidate
        """
        try:
            # Ensure tracking key exists
            _ensure_recompute_key(td)

            # Extract required fields
            input_ids = (
                td.get("input_ids", None) if hasattr(td, "get") else td.get("input_ids")
            )
            versions = (
                td.get("versions", None) if hasattr(td, "get") else td.get("versions")
            )
            loss_mask = (
                td.get("loss_mask", None) if hasattr(td, "get") else td.get("loss_mask")
            )
            prox_t = (
                td.get("proximal_logprobs_t", None)
                if hasattr(td, "get")
                else td.get("proximal_logprobs_t")
            )
            recompute_ver = (
                td.get(RECOMPUTE_VERSION_KEY, None)
                if hasattr(td, "get")
                else td.get(RECOMPUTE_VERSION_KEY)
            )

            if (
                input_ids is None
                or versions is None
                or loss_mask is None
                or prox_t is None
            ):
                return None

            # Check if already recomputed at this version
            # FIXME verify if (existing_ver == current_version) is enough.
            # What should we do when (existing_ver > current_version)? A warining should be issued in this case and
            # then return None
            if recompute_ver is not None:
                existing_ver = _extract_version(recompute_ver)
                if existing_ver == current_version:
                    return None  # Already recomputed

            # Extract first sequence (batch index 0)
            ids = (
                input_ids[0].tolist() if torch.is_tensor(input_ids[0]) else input_ids[0]
            )
            ver = versions[0].tolist() if torch.is_tensor(versions[0]) else versions[0]
            lm = (
                loss_mask[0].tolist() if torch.is_tensor(loss_mask[0]) else loss_mask[0]
            )

            # Get attention mask for valid length
            attn_mask = (
                td.get("attention_mask", None)
                if hasattr(td, "get")
                else td.get("attention_mask")
            )
            valid_len = len(ids)
            if attn_mask is not None:
                mask_row = attn_mask[0]
                if torch.is_tensor(mask_row):
                    mask_row = mask_row.tolist()
                try:
                    valid_len = mask_row.index(0) if 0 in mask_row else len(mask_row)
                except Exception:
                    valid_len = len(ids)

            # Find output positions with target version
            output_indices = []
            for idx in range(valid_len):
                if lm[idx] == 1 and ver[idx] == target_version:
                    output_indices.append(idx)

            if not output_indices:
                return None  # No candidates

            # Recompute logprobs
            full_ids = ids[:valid_len]
            new_logprobs = inference_engine.recompute_output_logprobs_sync(full_ids)

            if new_logprobs is None or len(new_logprobs) != len(full_ids):
                logger.warning(
                    f"Recompute returned unexpected result: "
                    f"expected {len(full_ids)}, got {len(new_logprobs) if new_logprobs else 0}"
                )
                return False

            # Patch prox_t at output positions
            for idx in output_indices:
                if hasattr(prox_t, "__setitem__"):
                    # TODO verify if this is the proper shape
                    prox_t[0, idx] = new_logprobs[idx]
                else:
                    logger.warning("Cannot patch prox_t: not writable")
                    return False

            # Mark as recomputed
            recompute_val = torch.full_like(
                versions[:, :1], current_version, dtype=torch.int64
            )
            if hasattr(td, "set"):
                td.set(RECOMPUTE_VERSION_KEY, recompute_val)
            else:
                td[RECOMPUTE_VERSION_KEY] = recompute_val

            logger.debug(
                f"Patched prox_t for {len(output_indices)} tokens at version {target_version}"
            )
            return True

        except Exception as e:
            logger.error(f"Error recomputing prox_t: {e}", exc_info=True)
            return False
